[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
ReinforcementLearningExperiments = "6bd458e5-1694-412f-b601-3a888375c491"
RollingFunctions = "b0e4dd01-7b14-53d8-9b45-175a3e362653"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
